# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: 'debug'
            XDEBUG_CONFIG: 'client_host=host.docker.internal client_port=9009 start_with_request=yes'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:5.7'
        ports:
            - '${FORWARD_DB_PORT:-3360}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    elasticsearch:
        build: ./docker/elasticsearch
        volumes:
            - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
            - ./docker/elasticsearch/config/dict.txt:/usr/share/elasticsearch/config/dict.txt
            - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
        environment:
            - TZ=Asia/Seoul
            - ELASTIC_PASSWORD=elasticpassword
            - node.name=elasticsearch
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - '9200:9200'
        networks:
            - sail
    kibana:
        build: ./docker/kibana
        environment:
            - TZ=Asia/Seoul
        volumes:
            - ./docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
        ports:
            - "5601:5601" ## 키바나의 기본포트는 5601 이다.
        networks:
            - sail
        depends_on:
            - elasticsearch
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
